version: '3.8'
services:
  postgresql:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - postgresql:/var/lib/postgresql/data
      
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      
  neo4j:
    image: neo4j:5.4.0-community
    restart: unless-stopped
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - 'neo4j_data:/data'
    environment:
      NEO4J_AUTH: neo4j/thisistheadminpassword
      
  cache:
    image: redis:7.0.8-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
volumes:
  postgresql:
    driver: local
  mongodb_data_container:
    driver: local
  neo4j_data:
    driver: local
  cache:
    driver: local